### ISSUE TITLE
core.entity_view_display.node.sa_page.teaser.yml has a dependency on layout_builder, but the recipe does not install it

### ISSUE THREAD

**Issue by thejimbirch** [kanopi/saplings-content-types#46]
There are some other configs also that also have this dependency.

Do we need Layout Builder for these display modes?  If so, we need to install it from the recipe.yml

If we do not need it, we need to remove it from third_party_settings and the dependencies section of each config that has it.

```
dependencies:
  config:
    - core.entity_view_mode.node.teaser
    - field.field.node.sa_page.sa_components
    - field.field.node.sa_page.sa_description
    - field.field.node.sa_page.sa_featured_media
    - field.field.node.sa_page.sa_header_position
    - field.field.node.sa_page.sa_hide_header
    - field.field.node.sa_page.sa_include_mute_button
    - field.field.node.sa_page.sa_include_pause_button
    - field.field.node.sa_page.sa_overlay
    - field.field.node.sa_page.sa_overlay_opacity
    - field.field.node.sa_page.sa_robots
    - field.field.node.sa_page.sa_seo_description
    - field.field.node.sa_page.sa_seo_image
    - field.field.node.sa_page.sa_seo_page_title
    - node.type.sa_page
  module:
    - ds
    - layout_builder
```

...

```
third_party_settings:
  sdc_display:
    enabled: false
    component:
      machine_name: ''
    mappings:
      static:
        props: {  }
        slots: {  }
      dynamic:
        props: {  }
        slots: {  }
  layout_builder:
    enabled: false
    allow_custom: false
```
